force-app/main/default/objects/Issue__c/Issue__c.object-meta.xml
<CustomObject>
    <description>Object to store issues (bigs, errors, feature requests) by users on the platform.</description>
    <label>Issue</label>
    <nameField>
        <displayFormat>I-{0000}</displayFormat>
        <label>Issue Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Issues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Issue__c/fields/Assigned_To__c.field-meta.xml
<CustomField>
    <fullName>Assigned_To__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Who is this issue assigned to?</description>
    <inlineHelpText>Who is this issue assigned to?</inlineHelpText>
    <label>Assigned To</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Issues</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Details__c.field-meta.xml
<CustomField>
    <fullName>Details__c</fullName>
    <description>Add summary details for the issue. For example: Copy/paste error, or feature request etc</description>
    <inlineHelpText>Add summary details for the issue. For example: Copy/paste error, or feature request etc</inlineHelpText>
    <label>Details</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Email_Notification__c.field-meta.xml
<CustomField>
    <fullName>Email_Notification__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Reporter can specify whether to receive email when issue is reported or status is updated</description>
    <inlineHelpText>Reporter can specify whether to receive email when issue is reported or status is updated</inlineHelpText>
    <label>Email Notification</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Expected_Result__c.field-meta.xml
<CustomField>
    <fullName>Expected_Result__c</fullName>
    <description>What was the outcome that you expected? Or expect if a feature request?</description>
    <inlineHelpText>What was the outcome that you expected? Or expect if a feature request?</inlineHelpText>
    <label>Expected Result</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>What is the priority for this issue? This will help admin respond appropriately.</description>
    <inlineHelpText>What is the priority for this issue? This will help admin respond appropriately.</inlineHelpText>
    <label>Priority</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Low</fullName>
                <default>true</default>
                <label>Low</label>
            </value>
            <value>
                <fullName>Medium</fullName>
            </value>
            <value>
                <fullName>High</fullName>
            </value>
            <value>
                <fullName>Critical</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Reported_Object__c.field-meta.xml
<CustomField>
    <fullName>Reported_Object__c</fullName>
    <description>Which object is this issue related to?</description>
    <inlineHelpText>Which object is this issue related to?</inlineHelpText>
    <label>Reported Object</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Reported_Record__c.field-meta.xml
<CustomField>
    <fullName>Reported_Record__c</fullName>
    <description>What record is this issue related to?</description>
    <inlineHelpText>What record is this issue related to?</inlineHelpText>
    <label>Reported Record</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Repro_Steps__c.field-meta.xml
<CustomField>
    <fullName>Repro_Steps__c</fullName>
    <description>Steps for admin to reproduce the issue</description>
    <inlineHelpText>Steps for admin to reproduce the issue</inlineHelpText>
    <label>Repro Steps</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <defaultValue>(&quot;New&quot;)</defaultValue>
    <description>What is the status of this issue?</description>
    <inlineHelpText>What is the status of this issue?</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Closed</fullName>
                <default>true</default>
                <label>Closed</label>
            </value>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Working</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>What is the type of this issue?</description>
    <inlineHelpText>What is the type of this issue?</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Bug</fullName>
                <default>true</default>
                <label>Bug</label>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Feature Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Issue__c/fields/URL__c.field-meta.xml
<CustomField>
    <fullName>URL__c</fullName>
    <description>Page URL where error was reported</description>
    <inlineHelpText>Page URL where error was reported</inlineHelpText>
    <label>URL</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/classes/IssueBox.cls
public with sharing class IssueBox {
     @AuraEnabled (cacheable = true)
    /**
     * Return list of issues; result will be paginated so records will be sent based on calculation of pageNumber and pageSize
     * totalrecords is NOT used but we pass it so we can refresh Wire method on lwc size when this changes
     * 
     * This method is cached because it's used in wire
     */
    public static List<Issue__c> getIssueList(Integer pageNumber, Integer pageSize, Integer totalrecords) {
        List<Issue__c> issueList = new List<Issue__c>(); 

        try{
            Integer offset = (pageSize * (pageNumber - 1));
            issueList = [SELECT 
                    ID, Name, Details__c, Email_Notification__c, Expected_Result__c, Priority__c, Reported_Object__c,
                    Reported_Record__c, Repro_Steps__c, Status__c, Type__c, URL__c, Assigned_To__c, Assigned_To__r.Name
                    FROM Issue__c WITH SECURITY_ENFORCED
                    ORDER BY Name DESC
                    limit :pageSize OFFSET :offset
                ];
        }catch(Exception e){ Util.log('IssueBox:getIssueList():Exception' + e.getMessage());}
        return issueList;
    }
	/**
	 * Return total issue records
	 * This count will be used for pagination
     * 
     * This method is cached because it's used in wire
	 */
    @AuraEnabled (cacheable = true)
    public static Integer getIssueCount() {  
        Integer count = 0;
        try{
            count = [SELECT count()  FROM Issue__c WITH SECURITY_ENFORCED];
        }catch(Exception e){ Util.log('IssueBox:getIssueList():Exception' + e.getMessage());}
        return count; 
    } 
}